"""user about_me

Revision ID: 9526597152a3
Revises: 71b1136ccba3
Create Date: 2019-05-04 18:08:03.606161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9526597152a3'
down_revision = '71b1136ccba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
